### ISSUE TITLE
human matting

### ISSUE THREAD

**Issue by Eason2Wang** [JizhiziLi/GFM#11]
Hi, can this work be used on human matting?

**Comment by 99991** [comment]
The pretrained model seems to generalize well for object outlines.

Input:

![Joe_Biden_official_portrait_2013_(cropped)](https://user-images.githubusercontent.com/18725165/100384616-d674d600-3020-11eb-8c89-eef5f0c83cf4.png)

Alpha:

![Joe_Biden_official_portrait_2013_(cropped)](https://user-images.githubusercontent.com/18725165/100384639-de347a80-3020-11eb-8039-cbfb6f1e4964.png)

Color:

![Joe_Biden_official_portrait_2013_(cropped)](https://user-images.githubusercontent.com/18725165/100384644-e2609800-3020-11eb-8f0c-b229924e1de3.png)

Alpha with estimated foreground:

![Joe_Biden_official_portrait_2013_(cropped)](https://user-images.githubusercontent.com/18725165/100384654-eab8d300-3020-11eb-860e-4cf4071b8ef7.png)

It would probably work even better when trained on a human dataset, e.g. https://github.com/lizhengwei1992/Semantic_Human_Matting

**Comment by JizhiziLi** [comment]
Hi @Eason2Wang , just like what @99991 said, our pre-trained model can be used to test on portrait images and can have good results. But it would be better if you can train the network from the beginning on a human dataset. Since the glance decoder and focus decoder are aiming at extracting semantic information and details, despite the categories. The network can be used to perform all-class end-to-end matting tasks, as long as you have sufficient training data. Thanks!

**Comment by yxt132** [comment]
> The pretrained model seems to generalize well for object outlines.
> 
> Input:
> 
> ![Joe_Biden_official_portrait_2013_(cropped)](https://user-images.githubusercontent.com/18725165/100384616-d674d600-3020-11eb-8c89-eef5f0c83cf4.png)
> 
> Alpha:
> 
> ![Joe_Biden_official_portrait_2013_(cropped)](https://user-images.githubusercontent.com/18725165/100384639-de347a80-3020-11eb-8039-cbfb6f1e4964.png)
> 
> Color:
> 
> ![Joe_Biden_official_portrait_2013_(cropped)](https://user-images.githubusercontent.com/18725165/100384644-e2609800-3020-11eb-8f0c-b229924e1de3.png)
> 
> Alpha with estimated foreground:
> 
> ![Joe_Biden_official_portrait_2013_(cropped)](https://user-images.githubusercontent.com/18725165/100384654-eab8d300-3020-11eb-860e-4cf4071b8ef7.png)
> 
> It would probably work even better when trained on a human dataset, e.g. https://github.com/lizhengwei1992/Semantic_Human_Matting

How did you estimate the foreground?

**Comment by 99991** [comment]
> How did you estimate the foreground?

https://pymatting.github.io/pymatting.foreground.html#module-pymatting.foreground.estimate_foreground_ml

**Comment by yxt132** [comment]
> > How did you estimate the foreground?
> 
> https://pymatting.github.io/pymatting.foreground.html#module-pymatting.foreground.estimate_foreground_ml

Cool, thanks!
