### ISSUE TITLE
How to calculate the composition loss when gaussian noise is added to the composited image?

### ISSUE THREAD

**Issue by eternalgogi92** [JizhiziLi/GFM#12]
Should we add the same gaussian noise to the composited predicted image as the composited ground truth image?

**Comment by eternalgogi92** [comment]
Or just ignore the noise

**Comment by JizhiziLi** [comment]
Hi @eternalgogi92 , the gaussian noise will need to add to the predicted composite image before calculating the composition loss if you have added the same noise to the ground truth composite image.

**Comment by eternalgogi92** [comment]
thanks
