### ISSUE TITLE
The number of blocks

### ISSUE THREAD

**Issue by zgd330** [JizhiziLi/GFM#14]
hi,
Thank you for uploading the net code!
In the architecture diagram of the paper, there are 4 blocks(E0~E4) in the enconder (including deconder), but in the code, two additional stages( including 3 resnet blocks) are added, there are 6 stages in total, should the code prevail?

**Comment by JizhiziLi** [comment]
Hi there, 

Sorry for the late reply, the code we provided now is the original encoder with two additional blocks, which is one of the three options of encoder we adopted: 1) ResNet-34; 2) DenseNet-121; 3) ResNet-34 with two additional blocks. You can find more detail in **section 6.4 - Results on the ORI-Track** in our paper(https://arxiv.org/pdf/2010.16188.pdf). 
 
We will release the network code of the other two encoders after the paper review, thanks!

Cheers,
Jizhizi Li
