### ISSUE TITLE
Expected date of Training code

### ISSUE THREAD

**Issue by ghost** [JizhiziLi/GFM#15]
Hi,
When is the paper review expected date?
Eagerly waiting for the training code to check out this exciting work

**Comment by JizhiziLi** [comment]
Hi there,

Thanks for showing interest in our work. Currently the paper is under review, we will release the training code and the AM-2k dataset after review. Unfortunately, we do not have an estimated time yet. 😢 


Cheers,
Jizhizi Li

**Comment by ghost** [comment]
Thanks, eagerly waiting for the same!
