### ISSUE TITLE
Could this be adapted for human matting?

### ISSUE THREAD

**Issue by antithing** [JizhiziLi/GFM#16]
Hi! great work! As this looks like a great approach, i was wondering if it would also work for human matting in teh same way?

Thanks!

**Comment by JizhiziLi** [comment]
Hi there,

Thanks for showing interest in our work, the network GFM can be used for all class matting as long as you have sufficient relevant training data, please refer to issue #11  as an example of adapting to human matting. 

Cheers
Jizhizi Li
