### ISSUE TITLE
about training code & human segmentation

### ISSUE THREAD

**Issue by vkl-git** [JizhiziLi/GFM#21]
When will the training code be released? Can this model be migrated to portrait segmentation?

**Comment by JizhiziLi** [comment]
Hi there, thanks for showing interest in our work, the paper is still under peer review, the training code will be released after the review.  

By the way, the network GFM can be migrated to all class matting including portrait as long as you have sufficient relevant training data, please refer to issue #11 as an example of adapting to human segmentation.
