### ISSUE TITLE
How to get high-quality annotated alpha mattes?

### ISSUE THREAD

**Issue by violet2020** [JizhiziLi/GFM#24]
Hi, thank you for your great work!
I want to generate high-quality alpha mattes like AM-2k  for other images, could you please tell me how to get them? Thanks!

**Comment by JizhiziLi** [comment]
Hi there, 

We manually annotate the labels using open-source image editing software, e.g. Adobe Photoshop, GIMP, etc. There are numerous tutorials online teaching how to do such things, here is a good one to get started https://www.youtube.com/watch?v=cSXKTXQI3HI&ab_channel=PHLEARN.
