### ISSUE TITLE
Will you publish AM-2K dataset?

### ISSUE THREAD

**Issue by shkarupa-alex** [JizhiziLi/GFM#25]
This paper published about 9 month ago and you already cite AM2K dataset in next paper (https://arxiv.org/pdf/2107.07235v1.pdf), but dataset is still not published
:(

**Comment by bluesky314** [comment]
+1 Any estimate on the release dates @JizhiziLi ?

**Comment by JizhiziLi** [comment]
Hi there, thanks for showing interest in our project. 

Unfortunately, the paper is still under a long peer review at this stage. Thus, we plan to release the AM2K dataset on a request basis by the end of the coming August. The access of AM2K will be changed to open after the peer review.

Please stay tuned to the GitHub page for the updates. Thanks!
