### ISSUE TITLE
Boundary problem

### ISSUE THREAD

**Issue by dreamer121121** [JizhiziLi/GFM#26]
I find that if i use the predict alpha multified with your initial image to get the color foreground, which is also the way used in your inference code, the final color foreground image will be surrounded by gray lines in boundary regions

**Comment by JizhiziLi** [comment]
Could you please share more details or maybe some examples of this case(in this issue or directly to my email jili8515@uni.sydney.edu.au)? Please make sure the predicted alpha does not have noise in boundary regions before generating the color foreground.

**Comment by cddlyf** [comment]
@JizhiziLi  hi, do you use any foreground estimation algorithm to estimate the color foreground? It seems that you directly use the original image as the foreground image.
