### ISSUE TITLE
Where can I find the data set you shared?

### ISSUE THREAD

**Issue by BJHYZJ** [JizhiziLi/GFM#29]
Thank you for sharing, your project is very interesting. I just read your paper carefully, and I want to use your data set to make some interesting projects (non-commercial). Where can I find the data set you shared?

**Comment by JizhiziLi** [comment]
Hi there, 

Thanks for showing interest in our project. The datasets AM-2k and BG-20k can be accessed from both Google drive and baidu wangpan, the links are available on the repo homepage. PM-10 will be available after privacy-preserving from the project Privacy-Preserving Portrait Matting(https://github.com/JizhiziLi/P3M) very soon, you can check out the GitHub repo for updates. Cheers.

**Comment by BJHYZJ** [comment]
Okay, thank you very much for your reply. This is the first time I have received a reply from the author of a private message. I am very happy, thank you sincerely, and wish you a happy life and success in your work.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JizhiziLi/GFM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月12日(星期五) 下午4:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JizhiziLi/GFM] Where can I find the data set you shared? (Issue #29)





 
Hi there,
 
Thanks for showing interest in our project. The datasets AM-2k and BG-2k can be accessed from both Google drive and baidu wangpan, the links are available on the repo homepage. PM-10 will be available after privacy-preserving from the project Privacy-Preserving Portrait Matting(https://github.com/JizhiziLi/P3M) very soon, you can check out the GitHub repo for updates. Cheers.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
