### ISSUE TITLE
Denoise dataset

### ISSUE THREAD

**Issue by caihaunqai** [JizhiziLi/GFM#30]
Hello, Thank you for your excellent work. I met some difficulties when denoise. Can you provide your dataset after denoising? Thank you~

**Comment by JizhiziLi** [comment]
Hi there,

We have updated the download links for am2k_fg_denoise and bg20k_denoise, you can checkout the download links from section Prepare Datasets in [this page](https://github.com/JizhiziLi/GFM/tree/master/core#prepare-datasets). Freel free to have a try, thanks!

**Comment by zoezhou1999** [comment]
Hi @JizhiziLi  why the bg20k_denoise data only contain 9000 images instead of 20k?
