### ISSUE TITLE
Looking forward to benchmark your work

### ISSUE THREAD

**Issue by SysDevHayes** [JizhiziLi/GFM#4]
Dear Jizhizili,
Thank you so much for your awesome work. I went through your demo images as well as your paper, very interesting results. Can't wait for the training code to really benchmark the capability of this architecture :p

**Comment by JizhiziLi** [comment]
Hi @EricLe-dev , thanks for showing interest in our paper! The training code will be released after the paper review. In the meantime, you are welcome to use our released inference code and a pretrained model to test on your sample images. :)
